artifacts_root: artifacts

#artifacts root is whenever downloading the data that save as folder abut when craete component that component will generate some artifacts that save in artifacts folder 
#inside that create one folder data ingestion
#download as zip and unzip it and present inside data ingestion component

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#inside artifacts create another folder prepare_base_modeland inside it download vgg16 base model
#then create thr custom layer and add also and make new model

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5